### ISSUE TITLE
volume_count and chapter_count not being retrieved from MyAnimeList

### ISSUE THREAD

**Issue by au5ton** [Nihilate/Acerola#2]
Attempting to retrieve [this manga](https://myanimelist.net/manga/31499) (as an example) gives `None` volumes and `1` chapters, but when I use `curl` on the MyAnimeList API directly I get: 
```xml
  <entry>
    ...
    <title>Nisekoi</title>
    ...
    <chapters>229</chapters>
    <volumes>25</volumes>
    ...
  </entry>
```

I suspect this has to do with [lines 126 to 131 of mal.py](https://github.com/Nihilate/Acerola/blob/master/Acerola/data_sources/mal.py#L126-L131), which I can't understand.

EDIT: /u/Roborugi has been able to process this exact manga before: [reddit permalink](https://www.reddit.com/r/manga/comments/6jqmxo/whats_the_most_satisfying_romance_manga_that/djgcdbw/). There you just used `find('chapters').text` and `find('volumes').text` instead.

**Comment by Nihilate** [comment]
This should now be resolved with https://github.com/Nihilate/Acerola/commit/bc4a55e7245d4b803a14c15b8bd67429b590358e
